import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  subsets: ['latin'], // Optimize for Latin characters
  weight: ['300', '400', '700'], // Choose font weights
  variable: '--font-nunito-sans' // Define a CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${nunitoSans.variable}`}>
       <Header/>
        {children}
      </body>
    </html>
  );
}
